apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  - "keycloak.yourdomain.example" # todo: adjust to your domain
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-admin
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: keycloak-admin-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  - "keycloak-admin.yourdomain.example" # todo: adjust to your domain
