apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-user
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-db-user
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kubernetes/test/db/keycloak-db-user # todo: adjust to your secret provider
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kubernetes/test/keycloak/keycloak-admin # todo: adjust to your secret provider