apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-900"
spec:
  description: Certs
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
  sourceRepos:
    - '*'
  destinations:
    - namespace: cert
      server: '*'
    - namespace: kube-system
      server: '*'