apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: "26.5.7"
    path: "kubernetes"
    directory:
      include: "kubernetes.yml"
      exclude: "{keycloakrealmimports.k8s.keycloak.org-v1.yml,keycloaks.k8s.keycloak.org-v1.yml}"
