apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/max-pfeiffer/proxmox-talos-opentofu.git # todo: adjust to your repo URL
    targetRevision: "main"
    path: "argocd/applications/keycloak-config"