apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "202"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmRef:
    name: homelab
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: argocd
  name: ArgoCD Client
  description: ""
  enabled: true
  public: false
  standardFlowEnabled: true
  implicitFlowEnabled: false
  fullScopeAllowed: true
  protocol: openid-connect
  clientAuthenticatorType: client-secret
  secret: $keycloak-client-argocd-secret:client-secret
  webUrl: "https://argocd.yourdomain.example" # todo: adjust to your domain
  adminUrl: "https://argocd.yourdomain.example" # todo: adjust to your domain
  homeUrl: /applications
  redirectUris:
    - "https://argocd.yourdomain.example/auth/callback" # todo: adjust to your domain
  webOrigins:
    - "https://argocd.yourdomain.example" # todo: adjust to your domain
  defaultClientScopes:
    - web-origins
    - acr
    - profile
    - roles
    - basic
    - email
    - groups
  optionalClientScopes:
    - address
    - phone
    - offline_access
    - organization
    - microprofile-jwt
