apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: groups
  annotations:
    argocd.argoproj.io/sync-wave: "202"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: groups
  realmRef:
    name: homelab
    kind: KeycloakRealm
  description: "When requested, this scope will map a user's group memberships to a claim"
  type: optional
  protocol: openid-connect
  attributes:
    include.in.token.scope: "true"
    display.on.consent.screen: "true"
    gui.order: ""
    consent.screen.text: "This scope will map a user's group memberships to a claim"
  protocolMappers:
    - name: group-membership-mapper
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "full.path": "false"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "claim.name": "groups"
        "userinfo.token.claim": "true"
        "multivalued": "true"