apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: max
  annotations:
    argocd.argoproj.io/sync-wave: "202"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmRef:
    name: homelab
    kind: KeycloakRealm
  # todo: adjust to your user
  username: "myusername"
  firstName: "myfirstname"
  lastName: "mylastname"
  email: "myemail@example.com"
  enabled: true
  emailVerified: true
  keepResource: true
  passwordSecret:
    name: keycloak-realm-user-max
    key: password
    temporary: false
  groups:
    - argocd-admins
