apiVersion: v1
kind: LimitRange
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256M
    defaultRequest:
      cpu: 10m
      memory: 32M
    max:
      cpu: 200m
      memory: 256M
    type: Container
