apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames: # todo: adjust to your domain
  - "argocd.yourdomain.example"
