apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: {{ .Values.ciliumLoadBalancerIpRange.start}}
      stop: {{ .Values.ciliumLoadBalancerIpRange.stop }}
