apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: cert
    server: https://kubernetes.default.svc
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.19.2
    helm:
      valuesObject:
        crds:
          enabled: true
        extraArgs:
          - "--enable-gateway-api"
