apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  externalIPs: true
  loadBalancerIPs: true