apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-user
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1"