apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: network
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  # Configure the FQDN for ArgoCD here
  - "argocd.yourdomain.com"
